### PR TITLE
[master]

### PR DESCRIPTION
**Pull request by williamdes**
Test PR

### CODE REVIEW

**Comment by williamdes** [comment]
@sudo-bot Deploy :)

**Comment by williamdes** [comment]
@sudo-bot /deploy

**Comment by williamdes** [comment]
@sudo-bot test, another one !

**Comment by williamdes** [comment]
@sudo-bot Deploy ?

**Comment by williamdes** [comment]
@sudo-bot Depoy PR :)

**Comment by williamdes** [comment]
@sudo-bot Deploy PR

**Comment by williamdes** [comment]
@sudo-bot

**Comment by williamdes** [comment]
@sudo-bot

**Comment by williamdes** [comment]
@sudo-bot D

**Comment by williamdes** [comment]
@sudo-bot DD

**Comment by williamdes** [comment]
@sudo-bot !

**Comment by williamdes** [comment]
@sudo-bot :)

**Comment by williamdes** [comment]
@sudo-bot :)

**Comment by williamdes** [comment]
@sudo-bot :)

**Comment by williamdes** [comment]
@sudo-bot :)

**Comment by williamdes** [comment]
@sudo-bot :)

**Comment by williamdes** [comment]
@sudo-bot :)

**Comment by williamdes** [comment]
@sudo-bot :))

**Comment by williamdes** [comment]
@sudo-bot :):)

**Comment by williamdes** [comment]
@sudo-bot ?

**Comment by williamdes** [comment]
@sudo-bot :)

**Comment by williamdes** [comment]
@sudo-bot /deploy

**Comment by williamdes** [comment]
a

**Comment by williamdes** [comment]
@sudo-bot

**Comment by williamdes** [comment]
hey @sudo-bot

**Comment by williamdes** [comment]
Hello @sudo-bot

**Comment by williamdes** [comment]
@sudo-bot PR

**Comment by williamdes** [comment]
@sudo-bot Deploy ?

**Comment by williamdes** [comment]
@sudo-bot /deploy

**Comment by williamdes** [comment]
@sudo-bot :)

**Comment by williamdes** [comment]
@sudo-bot ?

**Comment by williamdes** [comment]
@sudo-bot

**Comment by williamdes** [comment]
@sudo-bot

**Comment by williamdes** [comment]
@sudo-bot

**Comment by williamdes** [comment]
@sudo-bot ;)

**Comment by williamdes** [comment]
@sudo-bot /deploy

**Comment by williamdes** [comment]
@sudo-bot Deploy this PR

**Comment by williamdes** [comment]
@sudo-bot Deploy this PR

**Comment by williamdes** [comment]
@sudo-bot Deploy this PR

**Comment by williamdes** [comment]
@sudo-bot Deploy this PR

**Comment by williamdes** [comment]
@sudo-bot Deploy

**Comment by williamdes** [comment]
@sudo-bot /deploy

**Comment by williamdes** [comment]
@sudo-bot Deploy this PR

**Comment by williamdes** [comment]
@sudo-bot :)

**Comment by williamdes** [comment]
@sudp-bot /deploy

**Comment by williamdes** [comment]
@sudo-bot Deploy

**Comment by williamdes** [comment]
@sudo-bot Deploy PR

**Comment by williamdes** [comment]
@sudo-bot Deploy

**Comment by williamdes** [comment]
@sudo-bot Deploy pull-request

**Comment by williamdes** [comment]
@sudo-bot /deploy

**Comment by williamdes** [comment]
@sudo-bot Deploy

**Comment by williamdes** [comment]
@sudo-bot Deploy PR !

**Comment by williamdes** [comment]
@sudo-bot Deploy and use configuration:
```php
<?php
declare(strict_types=1);
$i = 0;
$i++;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = 'mariadb1.phpmyadmin.local';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = true;
```

**Comment by williamdes** [comment]
@sudo-bot Deploy and use configuration:
```php
<?php
declare(strict_types=1);
$i = 0;
$i++;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = 'mariadb1.phpmyadmin.local';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = true;
```

**Comment by williamdes** [comment]
@sudo-bot :)

**Comment by williamdes** [comment]
@sudo-bot Deploy and use configuration:
```php
<?php
declare(strict_types=1);
$i = 0;
$i++;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = 'mariadb1.phpmyadmin.local';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = true;
```

**Comment by williamdes** [comment]
@sudo-bot Deploy and use configuration:
```php
<?php
declare(strict_types=1);
$i = 0;
$i++;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = 'mariadb1.phpmyadmin.local';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = true;
```

**Comment by williamdes** [comment]
cc @kartik1000
@sudo-bot Deploy and use configuration:
```php
<?php
declare(strict_types=1);
$i = 0;
$i++;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = 'mariadb1.phpmyadmin.local';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = true;
```

**Comment by williamdes** [comment]
@sudo-bot Deploy and use configuration:
```php

<?php
declare(strict_types=1);
$i = 0;
$i++;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = 'mariadb1.phpmyadmin.local';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = true;
```

**Comment by williamdes** [comment]
cc @kartik1000
@sudo-bot Deploy and use configuration:
```php
<?php
declare(strict_types=1);
$i = 1;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = 'mariadb3.phpmyadmin.local';
```

**Comment by williamdes** [comment]
@sudo-bot Are you online ?

**Comment by williamdes** [comment]
Last try..
@sudo-bot Deploy with configuration:
```php
<?php
declare(strict_types=1);


```

**Comment by williamdes** [comment]
@sudo-bot deploy pr

**Comment by williamdes** [comment]
@sudo-bot Deploy PR

**Comment by williamdes** [comment]
@sudo-bot Deploy PR

**Comment by williamdes** [comment]
@sudo-bot Deploy pull-request

**Comment by williamdes** [comment]
@sudo-bot Deploy pull-request

**Comment by kartik1000** [comment]
@williamdes, Hey is there still something wrong that needs to be fixed? I thought its working fine now.

**Comment by williamdes** [comment]
@kartik1000 Yes, see: sudo-bot/gh-deployer#1

**Comment by williamdes** [comment]
@sudo-bot Deploy PR

**Comment by williamdes** [comment]
@sudo-bot Deploy pr

**Comment by williamdes** [comment]
@sudo-bot Deploy PR

**Comment by williamdes** [comment]
@sudo-bot Deploy PR

**Comment by kartik1000** [comment]
@williamdes, I think the sudo bot is repeatedly deploying the same PR but it needs to do so only once

**Comment by williamdes** [comment]
@kartik1000 Sorry for the spamming, I am trying to fix the installation of composer
Next enhancement is to update the previous deploy comment to avoid spamming :)

**Comment by kartik1000** [comment]
Hey, don't worry @williamdes, its no problem to me at all, i just thought i should let u know about its unusual behavior. Yes, that enhancement seems more than required to me :)

**Comment by williamdes** [comment]
@sudo-bot Deploy pull-request

**Comment by williamdes** [comment]
@sudo-bot Deploy

**Comment by williamdes** [comment]
@sudo-bot Deploy PR

**Pull request closed without merging**
